peaks:
  - EACH,ALL
resfrags:
  - /mnt/BioAdHoc/Groups/vd-ay/Database_HiChIP_eQTL_GWAS/Data/RefGenome/Restriction_Fragment/hg38/hg38_MboI_RE_Fragments.bed
hicpro_output:
  - /mnt/BioAdHoc/Groups/vd-ay/nrao/hichip_database/hicpro/ma_2021/HiCPro_Results